const express =require('express');
const router =express.Router();
const {create,read,remove,update,list,listRelated,listCategories,photo,listBySearch,listSearch}=require('../controllers/product');
const {requireSignin,isAuth,isAdmin}=require('../controllers/auth');
const {userById}=require('../controllers/user');
const {productById}=require('../controllers/product');
router.post('/product/create/:userId',requireSignin,isAuth,isAdmin,create);
router.get('/product/:productId',read);
router.get("/products/related/:productId", listRelated);
router.get('/products',list);
router.post("/products/by/search", listBySearch);
router.get("/products/search", listSearch);
router.get('/products/category',listCategories);
router.get('/product/photo/:productId',photo);
router.delete('/product/:productId/:userId',requireSignin,isAuth,isAdmin,remove);
router.put('/product/:productId/:userId',requireSignin,isAuth,isAdmin,update);
router.param("userId",userById);
router.param("productId",productById);
module.exports = router;